### ISSUE TITLE
Elden Ring Trainer, 1FPS outside the normal 16:9

### ISSUE THREAD

**Issue by Larsenist** [leaty/tuxtrain#2]
I don't know if it's even possible but could you unlock the FPS for the full 21:9 aspect ratio?
Anything outside of the normal 16:9 runs at 1 FPS

**Comment by leaty** [comment]
Unfortunately I couldn't reproduce this, using 3440x1440 as `Custom Resolution` and enabling `Aspect Ratio Unlock` and the other two features works fine with 100+ fps and no black bars.

It seems to me that this could be something else, are you sure all features apply and you're running it early enough (or using `tuxtraind` daemon)? Although, I should mention that I don't actually *have* an ultrawide screen so while I'm testing this- it just covers up a bit of the second monitor in Xorg instead.

One obscure thing you could try is using the new `-f` switch to ignore regions (again), and running `tuxtrain -f` *twice*. This is just in case your version of Elden Ring has multiple references to the same patterns, I highly highly doubt it, but you never know. But *if* so, it would patch two areas for at least one of the features, in which it's probably the region from the second run you want.

**Comment by Larsenist** [comment]
Sorry it took a while. I ran it 5 times and got the same regions.
It seems like it's just how the game is because in the ultra wide area everything goes at 1fps and when they enter the normal 16:9 area they sort of drop down and run normaly

larsen-pc ~\>>doas tuxtraind
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783].
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357].
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912].
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756].
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783].
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357].
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912].
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756].
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783].
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357].
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912].
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756].
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783].
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357].
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912].
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756].
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783].
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357].
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912].
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756].

**Comment by leaty** [comment]
Sorry if I wasn't clear enough, I meant you should start the game and run `tuxtrain -f` (*not* the daemon) *twice*, one after another without restarting the game. This should- if there aren't multiple references, output the following on the 2nd run:
```bash
leaty@arch:~$ sudo tuxtrain -f
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Error: Unable to find pattern.
	Hz Unlock
	  - Error: Unable to find pattern.
	Custom Resolution
	  - Error: Unable to find pattern.
	Aspect Ratio Unlock
	  - Error: Unable to find pattern.
```

If there are multiple references however, that will show up instead. Don't forget the `-f` switch or this test won't work. Also be aware, the 2nd run will likely be slow.

But now that I know what you mean with the 1 FPS outside the 16:9 view I can probably look to see if there's something I could do about it.

EDIT: Nope, as far as I could see, no one has found a way to patch the low fps enemies outside 16:9, not even in Sekiro it seems. Sadly I think it's going to stay that way, the game is hardwired to render *but at low fps* behind the black bars. Yes, fun fact: it's actually rendering behind the black bars for no reason even without the ultrawide patch which is actually insane. I'm sure it's *possible* to patch but if it doesn't exist for Sekiro yet it has to be very difficult to find.

**Comment by Larsenist** [comment]
Sorry, I forgot. Unable to find a pattern the second time. Also I've noticed that larger objects like trees aren't effected. It's only NPC's that run at 1 FPS.

larsen-pc tuxtrain\>>tuxtrain -f
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Location: 5383421775
	  - Found: C743208988883CEB
	  - Wrote: C74320600B363BEB
	  - Consider tightening region: [5383421775, 5383421783]
	Hz Unlock
	  - Location: 5395332341
	  - Found: EB0EC745EF3C000000C745F301000000
	  - Wrote: EB0EC745EF00000000C745F300000000
	  - Consider tightening region: [5395332341, 5395332357]
	Custom Resolution
	  - Location: 5429915896
	  - Found: 80070000380400000008000080040000
	  - Wrote: 700D0000A00500000008000080040000
	  - Consider tightening region: [5429915896, 5429915912]
	Aspect Ratio Unlock
	  - Location: 5395324739
	  - Found: 8B0185C07442448B59044585DB7439418B
	  - Wrote: 8B0185C0EB42448B59044585DB7439418B
	  - Consider tightening region: [5395324739, 5395324756]
larsen-pc tuxtrain\>>tuxtrain -f
==> Elden Ring Trainer 0.0.2
	FPS Unlock
	  - Error: Unable to find pattern.
	Hz Unlock
	  - Error: Unable to find pattern.
	Custom Resolution
	  - Error: Unable to find pattern.
	Aspect Ratio Unlock
	  - Error: Unable to find pattern.

**Comment by fipso** [comment]
Dosent er-patcher provide a patch for this ? https://github.com/gurrgur/er-patcher/blob/main/er-patcher#L81

**Comment by leaty** [comment]
I was very surprised, but increasing the animation distance *does* in fact seem to fix this as well! Thanks for finding it @fipso, I'll add it right away :+1:
